# Generated by Django 4.2.7 on 2026-04-07 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("firms", "0001_initial"),
        ("accounts", "0002_globalconfiguration"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFirmRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("platform_owner", "Platform Owner"),
                            ("partner_manager", "Partner Manager"),
                            ("super_admin", "Super Admin (Firm Owner)"),
                            ("admin", "Admin"),
                            ("advocate", "Advocate"),
                            ("paralegal", "Paralegal"),
                            ("client", "Client"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_last_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="firm_members",
                        to="firms.firm",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="firm_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "firm"], name="accounts_us_user_id_9a0cdf_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="accounts_us_is_acti_952e1c_idx"
                    ),
                ],
                "unique_together": {("user", "firm")},
            },
        ),
    ]
