# Generated by Django 4.2.7 on 2026-04-07 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("firms", "0002_branch"),
        ("accounts", "0003_userfirmrole"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfirmrole",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="branch_members",
                to="firms.branch",
            ),
        ),
    ]
