# Generated by Django 4.2.7 on 2026-04-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_userfirmrole_branch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinvitation",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
