# Generated by Django 4.2.7 on 2026-05-04 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("firms", "0003_add_logo_registration_practice_areas"),
        ("accounts", "0011_alter_customuser_consultation_fee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="firmjoinlink",
            name="solo_advocate",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when link is created by a solo advocate (no firm)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="solo_join_links",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="firmjoinlink",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_join_links",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="firmjoinlink",
            name="firm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="join_links",
                to="firms.firm",
            ),
        ),
    ]
