# Generated by Django 4.2.7 on 2026-04-22 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cases", "0008_alter_case_additional_expenses_and_more"),
        ("clients", "0003_client_profile_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("firms", "0003_add_logo_registration_practice_areas"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("hearing", "Court Hearing"),
                            ("meeting", "Meeting"),
                            ("deadline", "Deadline"),
                            ("task", "Task"),
                            ("consultation", "Client Consultation"),
                            ("filing", "Document Filing"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("rescheduled", "Rescheduled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                ("all_day", models.BooleanField(default=False)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("court_name", models.CharField(blank=True, max_length=255)),
                ("reminder_sent", models.BooleanField(default=False)),
                ("reminder_time", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assigned_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to="cases.case",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calendar_events",
                        to="clients.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to="firms.firm",
                    ),
                ),
            ],
            options={
                "ordering": ["start_datetime"],
                "indexes": [
                    models.Index(
                        fields=["firm", "start_datetime"],
                        name="calendar_ev_firm_id_40c20d_idx",
                    ),
                    models.Index(
                        fields=["event_type", "status"],
                        name="calendar_ev_event_t_a01d70_idx",
                    ),
                    models.Index(
                        fields=["start_datetime", "end_datetime"],
                        name="calendar_ev_start_d_ebf05b_idx",
                    ),
                ],
            },
        ),
    ]
