# Generated by Django 4.2.7 on 2026-05-06 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("firms", "0003_add_logo_registration_practice_areas"),
        ("calendar_events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendarevent",
            name="firm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calendar_events",
                to="firms.firm",
            ),
        ),
    ]
