# Generated by Django 4.2.7 on 2026-05-04 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("firms", "0003_add_logo_registration_practice_areas"),
        ("clients", "0003_client_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="solo_advocate",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when client is created by an advocate not under any law firm",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="solo_clients",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="firm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clients",
                to="firms.firm",
            ),
        ),
    ]
