# Generated by Django 4.2.7 on 2026-04-07 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("firms", "0002_branch"),
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="firm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to="firms.firm",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="resource_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="resource_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
